### PR TITLE
feat(multihreading): each url has it's own thread

### PR DESCRIPTION
**Pull request by aberenshtein**

### CODE REVIEW

**Comment by aberenshtein** [comment]
HI, we have more than 20 components on cachet and we didn't want to have a cachet-url-monitor service for each one so this PR opens a thread for each URL.
It's backward compatible so you can still monitor a single URL but I changed the config file to be compatible to multiple URLS.

Would love to get your thoughts on this pr and indeed you would like to merge it I would fix the tests

**Comment by aberenshtein** [comment]
@mtakaki

**Comment by mtakaki** [comment]
That's a really good solution, @aberenshtein! Do you think you could fix the broken unit tests? If so, I can merge it in.

**Comment by mtakaki** [comment]
If you grant me permission to edit the branch, I can try fixing the tests.

**Comment by dylie** [comment]
Does this work with the main build already?

**Comment by Leen15** [comment]
Hi, Any ETA here?

**Comment by mtakaki** [comment]
I guess I'll have to manually bring this branch over to this repo in order to fix the build. I'll give it a try...

**Comment by mtakaki** [comment]
I've moved this over to #76

**Pull request closed without merging**
