### PR TITLE
Update component status only when it has changed

### PR DESCRIPTION
**Pull request by jacekszubert**

### CODE REVIEW

**Comment by mtakaki** [comment]
This is not a bad idea, but if for whatever reason the status of a component is manually changed since it started, it won't be updated. I know this cold be an edge case, but it's a possibility.

What's your main concern with having it updating the status no matter what? Are you trying to reduce the outgoing traffic?

**Comment by jacekszubert** [comment]
Each status update (even to the same status) triggers email notifications to subscribers, which with current solution means a lot of mails being sent out until the component is fixed.

I'm aware it's not a perfect solution. The other one would be to check status stored by Cachet server on each endpoint test and push new one only if it's different, but it's not perfect either -- in this case any manual status update would be overwritten by url-monitor pretty soon.

**Comment by jacekszubert** [comment]
What are your thoughts on this @mtakaki? Maybe I'm missing some possible solution.

**Comment by mtakaki** [comment]
Sorry about the delay. You're right, that's a good point about spamming people. That's not an ideal situation and can be pretty annoying.
Lemme fix the build first, then I'll continue reviewing your PRs.

**Comment by inkadnb** [comment]
Can you please merge this in and push to docker? Thank you!

**Comment by mtakaki** [comment]
@inkadnb I've pretty swamped this year... I need to fix the build, before I can merge these PRs.
That's the only guarantee things are not breaking. I already merged some external PRs and they broke the build. I hope you understand it.

**Comment by theecodedragon** [comment]
Any update on this would be appreciated, I have reviewed the PR and this should potentially fix the spamming of emails back to back.

**Comment by mjonker92** [comment]
I would like to see this merged so I can enable subscriptions on Cachet, now it's just spamming me :sob:

**Comment by mtakaki** [comment]
I'm merging this, despite the build is currently broken. Still very swamped...

**Pull request merged**
